language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: K+IC2947Ya0/HZ9yTAXvNcE+02o0UxcTimN+E2sfEPPd4TlPPtU8GQZRK5i2scpj81jPRkXw9run/cGP/F2VbrzEpsFZGF/+wHaq1grkOL8CHfNDV7zr3brJAOeHDYuGhaU7nFHkONUzilaCRtvR9oZoeGm35Gi81a49Oj+gB4GBM2FcaZqMHJS8oeWq550DgyQ1IZZiuQSSksvEqoy3z9LnXmLbNyMRAQMv0nJzHQAtc71lOXREpU/iu/cWGdGo7/PA7TeH0cYwdpJNV0qnI3+hf4ExWzw07VfuHcepEA1TLgiGqNwsiSXcmhPgJCrsIFYsOY84ZXgts1C+hj/frBaealiIjM81VE7u+NLAPrTPRk0AP/CQm+o9nt0TFHtKJ5awTHuA6yaUN1NNJmRmYhdlfvoGOdqZhG/vbrulR6KC4x9ql8BA1WT/4G17amPZl8OQ1PKlB35b6M931Udnr1ZVvMebgvtI/OTf/1bGCvB3HRj2E+L5cpZtepsv36h3VxSLFBXQZQYjT5SfYOqJiifo+OrUwNETH/UuDWr+c9q2ktY5+0BB9FN3NxCg5N0dSK97GFrepm7AunZneUWxmhOuAqcRmXQd6tcbaZIVpT9K63hfiRg99tubDx51ogTah1dIrSlS66SdqQTgUMFktNsLW/4QFlLFHaC/00Dy6Cs=
  on:
    tags: true
    repo: DEGJS/urlUtils
