language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: IwwgtJEKFC1VXLHEiBo/9kT2aQy54uf1SJlCOPfit3OKDSqizU2v6zH+Hv4hioUotm162bmI3MvMq3mvd8369sgpAkCbayuiMYx0FG3eT0bnQ8PHkhRMSA+NS7fyBHIfT17OcU7P//RTomjmtBNz4Yc9yHAWrBGHp85uxksami71bRE1HrdnVD9v/KhLVNAU6H40D7j+gaGm+ayvi8b7sLXSU2k36aZdxRxhcMqDGma+AA/kxMS+ZzgH/XQt+rxaSM6OQi9q5i9kyf74kq6BCnYwB1bsXQ12JjJW3TuduBvFmQUjdbLqT/RvX2BU+5vdOGyQwjPdk/Yj1NnXpF4w1j4RA/SMvtXRvDA1KBuCo044ki3RGD/QtQ2gR2HPBtGw9edWCe7bu9apDm/UZzTj/QxL4ImUnYNHrs8mymzkiZguUVz8IphYSNRelv1LOil1C/nEpGQKOV18tupune9ll4h1GZLg3uR7p/CVSjrFKrfXtvM76oRt7kFYCrABZquMHlfSiSGd9N5hYq6tc+iGUjdbWIwd8zHbUN6iyQ16wwnthmCoXOH9zjQQEwXPJKyl52+JcG7fZiYrkNDBqHP/tCMFwQ2Q6OYfIVK+9uPZeZlyz965OHKLyjDZhSRKURvDc/jGnupu3r+fTponfTI6dgfd8G8zULA8idC1W2KXqxI=
  on:
    tags: true
    repo: DEGJS/urlUtils
